type Evidence = { kind:string; source:string; summary:string; confidence:number; artifact_uri?:string };
type CaseFile = { id:string; title:string; severity:string; status:string; asset:{name:string;chain:string;address:string;source_commit:string;block_snapshot:number;authority_summary:string}; policy_decision:string; policy_json:any; created_at:string };
type McpTool = { name:string; description:string; input_schema:any };
type CtfPlan = { source_url:string; host:string; mode:string; requires_login:boolean; network_execution:boolean; next_steps:string[]; policy:string };
const app = document.querySelector<HTMLElement>('#app')!;
const esc = (value:string) => value.replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]!));
async function api<T>(path:string, options?:RequestInit):Promise<T>{ const r=await fetch(path, options); if(!r.ok) throw new Error(await r.text()); return r.json(); }
function severityClass(s:string){return s.toLowerCase()==='high'||s.toLowerCase()==='critical'?'danger':'muted'}
function render(cases:CaseFile[], providers:any){
 app.innerHTML = `<div class="shell"><aside><div class="brand"><span class="mark">Ω</span><div><b>OMEGACLAW</b><small>autonomous security mesh</small></div></div><nav><a class="active">Case Files <span>${cases.length}</span></a><a>Asset Graph <span>SQLite</span></a><a>Evaluation <span>CTF</span></a><a>Policies <span>MeTTa</span></a></nav><div class="side-note"><span class="pulse"></span><div><b>Bounded autonomy</b><small>read-only / human-gated</small></div></div></aside><section class="content"><header><div><p class="eyebrow">SECURITY OPERATIONS / MVP</p><h1>ClawMesh console</h1><p class="lede">Evidence, policy, providers, and safe tool calls in one surface.</p></div><button id="refresh">Refresh <span>↻</span></button></header><section class="stats"><div><small>OPEN CASES</small><strong>${cases.length}</strong><em>SQLite persisted</em></div><div><small>HUMAN REVIEW</small><strong>${cases.filter(c=>c.policy_decision==='human_review_required').length}</strong><em>approval required</em></div><div><small>LLM BRIDGES</small><strong>${Object.values(providers).filter((v:any)=>v.configured).length}/3</strong><em>interchangeable adapters</em></div><div><small>MCP</small><strong id="mcp-status">OFF</strong><em>allowlisted read-only</em></div></section><section class="action-grid"><div class="action-card"><p class="eyebrow">CTF INTAKE</p><h3>Bring a challenge URL</h3><p>GitHub, HTB reference, or local fixture. No remote execution.</p><div class="inline-form"><input id="ctf-url" placeholder="https://github.com/org/ctf"/><button id="ctf-check">Validate</button></div><div id="ctf-result" class="result"></div></div><div class="action-card"><p class="eyebrow">MCP TOOLING</p><h3>Read-only server bridge</h3><p>Discover tools and call only configured allowlisted tools.</p><button id="mcp-list">Discover tools</button><div id="mcp-result" class="result"></div></div></section><div class="grid"><section class="panel"><div class="panel-head"><div><p class="eyebrow">INBOX / ${cases.length} ITEMS</p><h2>Active investigations</h2></div></div><div class="case-list">${cases.map((c,i)=>`<button class="case ${i===0?'selected':''}" data-id="${c.id}"><div class="case-top"><span class="dot ${severityClass(c.severity)}"></span><span class="tag ${severityClass(c.severity)}">${esc(c.severity)}</span><time>${new Date(c.created_at).toLocaleTimeString([], {hour:'2-digit',minute:'2-digit'})}</time></div><h3>${esc(c.title)}</h3><p>${esc(c.asset.name)} · ${esc(c.asset.chain)}</p><div class="case-foot"><span>${esc(c.policy_decision.replaceAll('_',' '))}</span><b>→</b></div></button>`).join('')}</div></section><section id="detail" class="panel detail"></section></div></section></div>`;
 document.querySelector('#refresh')?.addEventListener('click', load);
 document.querySelector('#ctf-check')?.addEventListener('click', validateCtf);
 document.querySelector('#mcp-list')?.addEventListener('click', discoverMcp);
 document.querySelectorAll<HTMLButtonElement>('.case').forEach(b=>b.addEventListener('click',()=>showDetail(cases.find(c=>c.id===b.dataset.id)!)));
 showDetail(cases[0]);
}
function showDetail(c:CaseFile|undefined){ const d=document.querySelector('#detail')!; if(!c){d.innerHTML='<div class="empty">No Case Files yet.</div>';return;} d.innerHTML=`<div class="panel-head"><div><p class="eyebrow">CASE FILE / ${c.id.slice(0,8)}</p><h2>Evidence dossier</h2></div><span class="status">● ${esc(c.policy_decision.replaceAll('_',' '))}</span></div><div class="hero"><span class="tag ${severityClass(c.severity)}">${esc(c.severity)} impact</span><h2>${esc(c.title)}</h2><p>Policy: ${esc(c.policy_decision)}. LLM output is advisory; Rust and MeTTa remain authoritative.</p></div><div class="detail-block"><h4>Asset identity</h4><dl><dt>Contract</dt><dd>${esc(c.asset.name)} <code>${esc(c.asset.address.slice(0,10))}…</code></dd><dt>Source snapshot</dt><dd><code>${esc(c.asset.source_commit)}</code> at block ${c.asset.block_snapshot.toLocaleString()}</dd><dt>Authority</dt><dd>${esc(c.asset.authority_summary)}</dd></dl></div><div class="detail-block"><h4>Policy JSON</h4><pre>${esc(JSON.stringify(c.policy_json,null,2))}</pre></div><div class="next"><b>Next safe step</b><span>Review evidence and run only an allowlisted local worker.</span></div>`; }
async function validateCtf(){ const input=document.querySelector<HTMLInputElement>('#ctf-url')!; const out=document.querySelector('#ctf-result')!; out.textContent='Validating metadata-only intake…'; try { const plan=await api<CtfPlan>('/api/ctf/import',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({url:input.value})}); out.innerHTML=`<b>${esc(plan.mode)}</b> · ${esc(plan.host)}<br>${plan.requires_login?'Login may be required for reference access.':'No login required for metadata.'}<br><small>${esc(plan.policy)}</small>`; } catch(e){out.textContent=String(e);} }
async function discoverMcp(){ const out=document.querySelector('#mcp-result')!; out.textContent='Discovering allowlisted tools…'; try { const data=await api<{configured:boolean;tools:McpTool[]}>('/api/mcp/tools'); const status=document.querySelector('#mcp-status'); if(status) status.textContent=data.configured?'ON':'OFF'; out.innerHTML=data.tools.length?data.tools.map(t=>`<article><b>${esc(t.name)}</b><small>${esc(t.description||'No description')}</small></article>`).join(''):'No allowlisted tools exposed.'; } catch(e){out.textContent=String(e);} }
async function load(){try{const [cases,providers]=await Promise.all([api<CaseFile[]>('/api/cases'),api<any>('/api/providers')]); render(cases,providers);}catch(e){app.innerHTML=`<div class="error">OmegaClaw API unavailable. Start the Rust service on port 8080.<br/><small>${esc(String(e))}</small></div>`;}}
load();
